# Cap 7 Limpeza e preparação dos dados

## 7.1 Manipulação de dados ausentes

In [1]:
import pandas as pd
import numpy as np


In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])


In [3]:
float_data


0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
# Método isna
float_data.isna()


0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])


In [6]:
string_data


0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()


0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data = pd.Series([1, 2, None], dtype="float64")


In [9]:
float_data


0    1.0
1    2.0
2    NaN
dtype: float64

In [10]:
float_data.isna()


0    False
1    False
2     True
dtype: bool

### Filtragem de dados ausentes

In [11]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])


In [12]:
data.dropna()


0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notna()]


0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame(
    [
        [1.0, 6.5, 3.0],
        [1.0, np.nan, np.nan],
        [np.nan, np.nan, np.nan],
        [np.nan, 6.5, 3.0],
    ]
)


In [15]:
data


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data.dropna()


0    1    2
0  1.0  6.5  3.0

In [17]:
data.dropna(how="all")


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data[4] = np.nan


In [19]:
data


0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [20]:
data.dropna(axis="columns", how="all")


0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [21]:
# Parâmetro thresh
df = pd.DataFrame(np.random.standard_normal((7, 3)))


In [22]:
df.iloc[:4, 1] = np.nan


In [23]:
df.iloc[:2, 2] = np.nan


In [24]:
df


0         1         2
0  0.130050       NaN       NaN
1 -0.469552       NaN       NaN
2  1.010539       NaN  0.345442
3 -0.813280       NaN  1.264962
4  0.344388  0.745373  0.716738
5  2.335198  0.593265 -0.256350
6 -1.104091  0.230169 -1.321279

In [25]:
df.dropna()


0         1         2
4  0.344388  0.745373  0.716738
5  2.335198  0.593265 -0.256350
6 -1.104091  0.230169 -1.321279

In [26]:
df.dropna(thresh=2)


0         1         2
2  1.010539       NaN  0.345442
3 -0.813280       NaN  1.264962
4  0.344388  0.745373  0.716738
5  2.335198  0.593265 -0.256350
6 -1.104091  0.230169 -1.321279

### Preenchendo dados ausentes

In [27]:
# Método fillna
df.fillna(0)


0         1         2
0  0.130050  0.000000  0.000000
1 -0.469552  0.000000  0.000000
2  1.010539  0.000000  0.345442
3 -0.813280  0.000000  1.264962
4  0.344388  0.745373  0.716738
5  2.335198  0.593265 -0.256350
6 -1.104091  0.230169 -1.321279

In [28]:
df.fillna({1: 0.5, 2: 0})


0         1         2
0  0.130050  0.500000  0.000000
1 -0.469552  0.500000  0.000000
2  1.010539  0.500000  0.345442
3 -0.813280  0.500000  1.264962
4  0.344388  0.745373  0.716738
5  2.335198  0.593265 -0.256350
6 -1.104091  0.230169 -1.321279

In [29]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))


In [30]:
df.iloc[2:, 1] = np.nan


In [31]:
df.iloc[4:, 2] = np.nan


In [32]:
df


0         1         2
0  0.919218  0.259411  0.447183
1 -1.135455 -0.248360  0.013207
2  0.262841       NaN  0.211149
3 -0.071593       NaN  0.268077
4  0.420526       NaN       NaN
5 -1.560974       NaN       NaN

In [33]:
df.fillna(method="ffill")


C:\Users\derek\AppData\Local\Temp\ipykernel_11964\4105657595.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0  0.919218  0.259411  0.447183
1 -1.135455 -0.248360  0.013207
2  0.262841 -0.248360  0.211149
3 -0.071593 -0.248360  0.268077
4  0.420526 -0.248360  0.268077
5 -1.560974 -0.248360  0.268077

In [34]:
df.fillna(method="ffill", limit=2)


C:\Users\derek\AppData\Local\Temp\ipykernel_11964\3889071623.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)


0         1         2
0  0.919218  0.259411  0.447183
1 -1.135455 -0.248360  0.013207
2  0.262841 -0.248360  0.211149
3 -0.071593 -0.248360  0.268077
4  0.420526       NaN  0.268077
5 -1.560974       NaN  0.268077

In [35]:
data = pd.Series([1.0, np.nan, 3.5, np.nan, 7])


In [36]:
data.fillna(data.mean())


0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 Transformação de dados

### Remoção de duplicidades

In [37]:
data = pd.DataFrame(
    {"k1": ["one", "two"] * 3 + ["two"], "k2": [1, 1, 2, 3, 3, 4, 4]}
)


In [38]:
data


k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [39]:
# Método duplicated
data.duplicated()


0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [40]:
# Método drop_duplicates
data.drop_duplicates()


k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [41]:
data["v1"] = range(7)


In [42]:
data


k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [43]:
data.drop_duplicates(subset=["k1"])


k1  k2  v1
0  one   1   0
1  two   1   1

In [44]:
data.drop_duplicates(["k1", "k2"], keep="last")


k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transformação de dados com o uso de uma função ou mapeamento

In [45]:
data = pd.DataFrame(
    {
        "food": [
            "bacon",
            "pulled pork",
            "bacon",
            "pastrami",
            "corned beef",
            "bacon",
            "pastrami",
            "honey ham",
            "nova lox",
        ],
        "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6],
    }
)


In [46]:
data


food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon",
}


In [48]:
# Método map
data["animal"] = data["food"].map(meat_to_animal)


In [49]:
data


food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [50]:
def get_animal(x):
    return meat_to_animal[x]


In [51]:
data["food"].map(get_animal)


0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Substituição de valores

In [52]:
data = pd.Series([1.0, -999.0, 2.0, -999.0, -1000.0, 3.0])


In [53]:
data


0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [54]:
# Método replace
data.replace(-999, np.nan)


0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace([-999, -1000], np.nan)


0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [56]:
data.replace([-999, -1000], [np.nan, 0])


0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [57]:
data.replace({-999: np.nan, -1000: 0})


0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renomeação dos índices dos eixos

In [58]:
data = pd.DataFrame(
    np.arange(12).reshape((3, 4)),
    index=["Ohio", "Colorado", "New York"],
    columns=["one", "two", "three", "four"],
)


In [59]:
def transform(x):
    return x[:4].upper()


In [60]:
data.index.map(transform)


Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [61]:
data.index = data.index.map(transform)


In [62]:
data


one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [63]:
# Método rename
data.rename(index=str.title, columns=str.upper)


ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [64]:
data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"})


one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretização e compartimentalização

In [65]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]


In [66]:
bins = [18, 25, 35, 60, 100]


In [67]:
age_categories = pd.cut(ages, bins)


In [68]:
age_categories


[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [69]:
age_categories.codes


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [70]:
age_categories.categories


IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [71]:
age_categories.categories[0]


Interval(18, 25, closed='right')

In [72]:
pd.value_counts(age_categories)


C:\Users\derek\AppData\Local\Temp\ipykernel_11964\3004322060.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [73]:
pd.cut(ages, bins, right=False)


[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [74]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]


In [75]:
pd.cut(ages, bins, labels=group_names)


['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [76]:
data = np.random.uniform(size=20)


In [77]:
pd.cut(data, 4, precision=2)


[(0.49, 0.73], (0.73, 0.97], (0.49, 0.73], (0.25, 0.49], (0.49, 0.73], ..., (0.73, 0.97], (0.73, 0.97], (0.49, 0.73], (0.49, 0.73], (0.25, 0.49]]
Length: 20
Categories (4, interval[float64, right]): [(0.0071, 0.25] < (0.25, 0.49] < (0.49, 0.73] < (0.73, 0.97]]

In [78]:
data = np.random.standard_normal(1000)


In [79]:
quartiles = pd.qcut(data, 4, precision=2)


In [80]:
quartiles


[(-0.7, -0.0074], (-0.0074, 0.64], (-0.0074, 0.64], (-3.44, -0.7], (-3.44, -0.7], ..., (-3.44, -0.7], (0.64, 2.96], (-0.0074, 0.64], (-0.0074, 0.64], (-0.0074, 0.64]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.44, -0.7] < (-0.7, -0.0074] < (-0.0074, 0.64] < (0.64, 2.96]]

In [81]:
pd.value_counts(quartiles)


C:\Users\derek\AppData\Local\Temp\ipykernel_11964\3327749678.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-3.44, -0.7]      250
(-0.7, -0.0074]    250
(-0.0074, 0.64]    250
(0.64, 2.96]       250
Name: count, dtype: int64

In [82]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.0]).value_counts()


(-3.4339999999999997, -1.345]    100
(-1.345, -0.00743]               400
(-0.00743, 1.231]                400
(1.231, 2.955]                   100
Name: count, dtype: int64

### Detecção e filtragem de valores discrepantes

In [83]:
data = pd.DataFrame(np.random.standard_normal((100, 4)))


In [84]:
data.describe()


0           1           2           3
count  100.000000  100.000000  100.000000  100.000000
mean    -0.021230   -0.004563   -0.129934   -0.103004
std      1.017199    0.916284    0.962418    1.008828
min     -2.466355   -2.116609   -2.375298   -2.529709
25%     -0.635401   -0.573389   -0.648502   -0.837434
50%     -0.091816   -0.044965   -0.135079   -0.078649
75%      0.598443    0.581981    0.550532    0.461813
max      2.482689    2.389265    1.953698    2.241519

In [85]:
col = data[2]


In [86]:
col[col.abs() > 3]


Series([], Name: 2, dtype: float64)

In [87]:
# Método any
data[(data.abs() > 3).any(axis="columns")]


Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [88]:
data[data.abs() > 3] = np.sign(data) * 3


In [89]:
data.describe()


0           1           2           3
count  100.000000  100.000000  100.000000  100.000000
mean    -0.021230   -0.004563   -0.129934   -0.103004
std      1.017199    0.916284    0.962418    1.008828
min     -2.466355   -2.116609   -2.375298   -2.529709
25%     -0.635401   -0.573389   -0.648502   -0.837434
50%     -0.091816   -0.044965   -0.135079   -0.078649
75%      0.598443    0.581981    0.550532    0.461813
max      2.482689    2.389265    1.953698    2.241519

In [90]:
np.sign(data).head()


0    1    2    3
0 -1.0  1.0 -1.0  1.0
1  1.0 -1.0 -1.0 -1.0
2  1.0  1.0 -1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0  1.0

### Permutação e amostragem aleatória

In [91]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))


In [92]:
df


0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [93]:
sampler = np.random.permutation(5)


In [94]:
sampler


array([2, 3, 0, 1, 4], dtype=int32)

In [95]:
df.take(sampler)


0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [96]:
df.iloc[sampler]


0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [97]:
column_sampler = np.random.permutation(7)


In [98]:
column_sampler


array([0, 5, 3, 2, 1, 6, 4], dtype=int32)

In [99]:
df.take(column_sampler, axis="columns")


0   5   3   2   1   6   4
0   0   5   3   2   1   6   4
1   7  12  10   9   8  13  11
2  14  19  17  16  15  20  18
3  21  26  24  23  22  27  25
4  28  33  31  30  29  34  32

In [100]:
df.sample(n=3)


0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [101]:
choices = pd.Series([5, 7, -1, 6, 4])


In [102]:
choices.sample(n=10, replace=True)


4    4
0    5
1    7
1    7
3    6
2   -1
1    7
1    7
1    7
2   -1
dtype: int64

### Cálculo de variáveis indicadoras/dummy

In [103]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"], "data1": range(6)})


In [104]:
df


key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [105]:
pd.get_dummies(df["key"], dtype=int)


a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [106]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=int)


In [107]:
df_with_dummy = df[["data1"]].join(dummies)


In [108]:
df_with_dummy


data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [109]:
mnames = ["movie_id", "title", "genres"]


In [110]:
movies = pd.read_table(
    "datasets/movielens/movies.dat",
    sep="::",
    header=None,
    names=mnames,
    engine="python",
)


In [111]:
movies[:10]


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [112]:
dummies = movies["genres"].str.get_dummies("|")


In [113]:
dummies.iloc[:10, :6]


Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [114]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))


In [115]:
movies_windic.iloc[0]


movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [116]:
np.random.seed(12345)


In [117]:
values = np.random.uniform(size=10)


In [118]:
values


array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [119]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]


In [120]:
pd.get_dummies(pd.cut(values, bins), dtype=int)


(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3 Tipos de dados de extensão

In [121]:
s = pd.Series([1, 2, 3, None])


In [122]:
s


0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [123]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())


In [124]:
s


0       1
1       2
2       3
3    <NA>
dtype: Int64

In [125]:
s.isna()


0    False
1    False
2    False
3     True
dtype: bool

In [126]:
s.dtype


Int64Dtype()

In [127]:
s[3]


<NA>

In [128]:
s[3] is pd.NA


True

In [129]:
s = pd.Series([1, 2, 3, None], dtype="Int64")


In [130]:
s = pd.Series(["one", "two", None, "three"], dtype=pd.StringDtype())


In [131]:
s


0      one
1      two
2     <NA>
3    three
dtype: string

In [132]:
df = pd.DataFrame(
    {
        "A": [1, 2, None, 4],
        "B": ["one", "two", "three", None],
        "C": [False, None, False, True],
    }
)


In [133]:
df


A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [134]:
df["A"] = df["A"].astype("Int64")


In [135]:
df["B"] = df["B"].astype("string")


In [136]:
df["C"] = df["C"].astype("boolean")


In [137]:
df


A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## 7.4 Manipulação de strings

### Métodos internos dos objetos de string Python

In [138]:
val = "a,b, guido"


In [139]:
val.split(",")


['a', 'b', ' guido']

In [140]:
pieces = [x.strip() for x in val.split(",")]


In [141]:
pieces


['a', 'b', 'guido']

In [142]:
first, second, third = pieces


In [143]:
first + "::" + second + "::" + third


'a::b::guido'

In [144]:
"::".join(pieces)


'a::b::guido'

In [145]:
"guido" in val


True

In [146]:
val.index(",")


1

In [147]:
val.find(":")


-1

In [148]:
val.index(":")


ValueError: substring not found

In [ ]:
val.count(",")


2

In [ ]:
val.replace(",", "::")


'a::b:: guido'

In [ ]:
val.replace(",", "")


'ab guido'

### Expressões regulares

In [ ]:
import re


In [ ]:
text = "foo bar\t baz   \tqux"


In [ ]:
re.split(r"\s+", text)


['foo', 'bar', 'baz', 'qux']

In [ ]:
regex = re.compile(r"\s+")


In [ ]:
regex.split(text)


['foo', 'bar', 'baz', 'qux']

In [ ]:
regex.findall(text)


[' ', '\t ', '   \t']

In [ ]:
text = """
Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE faz com que a regex não diferencie leras maiúsculas de letras
# minúsculas
regex = re.compile(pattern, flags=re.IGNORECASE)


In [ ]:
regex.findall(text)


['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [ ]:
m = regex.search(text)


In [ ]:
m


<re.Match object; span=(6, 21), match='dave@google.com'>

In [ ]:
text[m.start() : m.end()]


'dave@google.com'

In [ ]:
print(regex.match(text))


None


In [ ]:
print(regex.sub("REDACTED", text))



Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [ ]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"


In [ ]:
regex = re.compile(pattern, flags=re.IGNORECASE)


In [ ]:
m = regex.match("wesm@bright.net")


In [ ]:
m.groups()


('wesm', 'bright', 'net')

In [ ]:
regex.findall(text)


[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [ ]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))



Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### Funções de string do pandas

In [ ]:
data = {
    "Dave": "dave@google.com",
    "Steve": "steve@gmail.com",
    "Rob": "rob@gmail.com",
    "Wes": np.nan,
}


In [ ]:
data = pd.Series(data)


In [ ]:
data


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [ ]:
data.isna()


Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [ ]:
data.str.contains("gmail")


Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [ ]:
data_as_string_ext = data.astype("string")


In [ ]:
data_as_string_ext


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [ ]:
data_as_string_ext.str.contains("gmail")


Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [ ]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"


In [ ]:
data.str.findall(pattern, flags=re.IGNORECASE)


Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [ ]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]


In [ ]:
matches


Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [ ]:
matches.str.get(1)


Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [ ]:
data.str[:5]


Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [ ]:
data.str.extract(pattern, flags=re.IGNORECASE)


0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

## 7.5 Dados categóricos 

In [149]:
values = pd.Series(["apple", "orange", "apple", "apple"] * 2)


In [ ]:
values


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [ ]:
pd.unique(values)


array(['apple', 'orange'], dtype=object)

In [ ]:
pd.value_counts(values)


C:\Users\derek\AppData\Local\Temp\ipykernel_11964\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [153]:
values = pd.Series([0, 1, 0, 0] * 2)


In [154]:
dim = pd.Series(["apple", "orange"])


In [ ]:
values


0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [ ]:
dim


0     apple
1    orange
dtype: object

In [ ]:
dim.take(values)


0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### Tipo de extensão Categorical do pandas

In [158]:
fruits = ["apple", "orange", "apple", "apple"] * 2


In [ ]:
N = len(fruits)


In [160]:
rng = np.random.default_rng(seed=12345)


In [161]:
df = pd.DataFrame(
    {
        "fruit": fruits,
        "basket_id": np.arange(N),
        "count": rng.integers(3, 15, size=N),
        "weight": rng.uniform(0, 4, size=N),
    },
    columns=["basket_id", "fruit", "count", "weight"],
)


In [ ]:
df


basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [163]:
fruit_cat = df["fruit"].astype("category")


In [ ]:
fruit_cat


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [ ]:
c = fruit_cat.array


In [ ]:
type(c)


pandas.core.arrays.categorical.Categorical

In [ ]:
c.categories


Index(['apple', 'orange'], dtype='object')

In [ ]:
c.codes


array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [169]:
dict(enumerate(c.categories))


{0: 'apple', 1: 'orange'}

In [170]:
df["fruit"] = df["fruit"].astype("category")


In [ ]:
df["fruit"]


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [172]:
my_categories = pd.Categorical(["foo", "bar", "baz", "foo", "bar"])


In [ ]:
my_categories


['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [174]:
categories = ["foo", "bar", "baz"]


In [175]:
codes = [0, 1, 2, 0, 0, 1]


In [176]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)


In [ ]:
my_cats_2


['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [178]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)


In [ ]:
ordered_cat


['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [ ]:
my_cats_2.as_ordered()


['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

### Computações com categóricos

In [181]:
rng = np.random.default_rng(seed=12345)


In [182]:
draws = rng.standard_normal(1000)


In [183]:
draws[:5]


array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [184]:
bins = pd.qcut(draws, 4)


In [ ]:
bins


[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [186]:
bins = pd.qcut(draws, 4, labels=["Q1", "Q2", "Q3", "Q4"])


In [ ]:
bins


['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [188]:
bins.codes[:10]


array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [189]:
bins = pd.Series(bins, name="quartile")


In [190]:
results = (
    pd.Series(draws).groupby(bins).agg(["count", "min", "max"]).reset_index()
)


C:\Users\derek\AppData\Local\Temp\ipykernel_11964\2835731488.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pd.Series(draws).groupby(bins).agg(["count", "min", "max"]).reset_index()


In [ ]:
results


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [ ]:
results["quartile"]


0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

#### Melhor desempenho com categóricos

In [ ]:
N = 10_000_000


In [194]:
labels = pd.Series(["foo", "bar", "baz", "qux"]) * (N // 4)


In [ ]:
categories = labels.astype("category")


In [ ]:
labels.memory_usage(deep=True)


30000356

In [ ]:
categories.memory_usage(deep=True)


30000532

In [198]:
%time _ = labels.astype("category")


CPU times: total: 93.8 ms
Wall time: 204 ms


In [202]:
%timeit labels.value_counts()


270 µs ± 24.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [203]:
%timeit categories.value_counts()


399 µs ± 20.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Métodos categóricos

In [213]:
s = pd.Series(["a", "b", "c", "d"] * 2)


In [214]:
cat_s = s.astype("category")


In [215]:
cat_s


0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [216]:
cat_s.cat.codes


0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [217]:
cat_s.cat.categories


Index(['a', 'b', 'c', 'd'], dtype='object')

In [218]:
actual_categories = ["a", "b", "c", "d", "e"]


In [219]:
cat_s2 = cat_s.cat.set_categories(actual_categories)


In [ ]:
cat_s2


0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [ ]:
cat_s.value_counts()


a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [ ]:
cat_s2.value_counts()


a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [224]:
cat_s3 = cat_s[cat_s.isin(["a", "b"])]


In [ ]:
cat_s3


0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
cat_s3.cat.remove_unused_categories()


0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

#### Criação de variáveis dummy para modelagem

In [227]:
cat_s = pd.Series(["a", "b", "c", "d"] * 2, dtype="category")


In [229]:
pd.get_dummies(cat_s, dtype=int)


a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1